
package net.webservicex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CookingUnitSoap", targetNamespace = "http://www.webserviceX.NET/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CookingUnitSoap {


    /**
     * 
     * @param cookingValue
     * @param fromCookingUnit
     * @param toCookingUnit
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ChangeCookingUnit", action = "http://www.webserviceX.NET/ChangeCookingUnit")
    @WebResult(name = "ChangeCookingUnitResult", targetNamespace = "http://www.webserviceX.NET/")
    @RequestWrapper(localName = "ChangeCookingUnit", targetNamespace = "http://www.webserviceX.NET/", className = "net.webservicex.ChangeCookingUnit")
    @ResponseWrapper(localName = "ChangeCookingUnitResponse", targetNamespace = "http://www.webserviceX.NET/", className = "net.webservicex.ChangeCookingUnitResponse")
    public double changeCookingUnit(
        @WebParam(name = "CookingValue", targetNamespace = "http://www.webserviceX.NET/")
        double cookingValue,
        @WebParam(name = "fromCookingUnit", targetNamespace = "http://www.webserviceX.NET/")
        Cookings fromCookingUnit,
        @WebParam(name = "toCookingUnit", targetNamespace = "http://www.webserviceX.NET/")
        Cookings toCookingUnit);

}
